### ISSUE TITLE
replace `hono` and revert to just api routes

### ISSUE THREAD

**Issue by AmoabaKelvin** [AmoabaKelvin/ishortn.ink#100]
Hono was intended to be used, but as things stand, we rarely use anything specific to the library, with the exception of the middleware, when checking a user's authentication status when using the dynamic links API.

To make things much simpler and more beginner-friendly, we intend to return to using only Nextjs API route handlers.

**Comment by BreakTos** [comment]
Hi, I want to take this issue up. Just need to get the project running locally for which i apparently need CLERK KEY and UNKEY??

**Comment by AmoabaKelvin** [comment]
@BreakTos 
The Docker image is to help set up the database that you will need to get things up and running. 

I wrote some documentation about how to set things up, but there needs to be some updates in the docs. You can find the link here: https://ishortn.ink/docs. I'm working very hard to improve the whole DX so hopefully things get better.

One thing you might not see however is the part related to UPSTASH. So you will need to follow this walkthrough to help set it up: https://upstash.com/docs/redis/overall/getstarted

Please let me know if you need further assistance at any point, I'm here to help.

**Comment by BreakTos** [comment]
Cool, i managed to set the variables and sign up with clerk is working. However weirdly the /dashboard of original site deployed and mine is way too different at same route somehow. Attaching screenshots

![image](https://github.com/AmoabaKelvin/ishortn.ink/assets/76687690/19817eea-1271-4d65-81f6-a79512edc039)

**Comment by AmoabaKelvin** [comment]
the reason is that there is no user in the database by your ID.

The way this is resolved is to go to your clerk dashboard, and to the users section, you then click on the user and then copy the user ID.

![CleanShot 2024-03-28 at 06 51 13@2x](https://github.com/AmoabaKelvin/ishortn.ink/assets/97001695/63d11462-c591-43db-bbf3-1cfb3a558a19)

The next thing will be to run `prisma db push` and then `prisma studio`.

Once prisma studio launches, please go ahead to the users table and create a new user with the ID you copied. Once done, it should work very fine.
