### ISSUE TITLE
link vanished from dashboard, but still works.

### ISSUE THREAD

**Issue by ThePaywalledKnowledge** [AmoabaKelvin/ishortn.ink#117]
as title says, still works and still redirects, but it doesn't appear on the dashboard anymore.

steps tried to solve the issue:
- tried clearing browser chaches;
- tried relogging in the account;
- tried logging in on a different device.

doesn't appear still.

step to reproduce the issue:
none. happened randomly without a possible reproducing logic.

**Comment by AmoabaKelvin** [comment]
Apologies for the late reply, pal. Can you please share the link that disappeared with me so I can look further into it. You can share it via email if you wish: kelvin@ishortn.ink.
