### ISSUE TITLE
Google chrome shows the red screen of “ Dangerous site”

### ISSUE THREAD

**Issue by MinhazI** [AmoabaKelvin/ishortn.ink#172]
**Describe the bug**
When we visit the shortened URL or even ishortn.ink’s website, Google chrome shows the red screen of “ Dangerous site” which is taking a hit for us as it says “Attackers on the site you're trying to visit might trick you into installing software or revealing things like your password, phone, or credit card number. Chrome strongly recommends going back to safety.”

**To Reproduce**
1. Go to 'ishortn.ink’ or any shortened url via ishortn
2. See error

**Expected behavior**
It should load the original url, but instead it shows the red warning acreen

**Screenshots**
<img width="414" alt="image" src="https://github.com/user-attachments/assets/72b5ca4f-7bd9-413d-abde-b3501123f77e">

**Desktop (please complete the following information):**
 - OS: all OS
 - Browser: Chrome
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: All devices 
 - OS: All OS
 - Browser: Chrome
 - Version: N/A

**Comment by richycala** [comment]
We are facing the same issue. Not looking good at all.  Please fix this. Thank you!

**Comment by AmoabaKelvin** [comment]
fixed
