### ISSUE TITLE
Features section on the homepage

### ISSUE THREAD

**Issue by AmoabaKelvin** [AmoabaKelvin/ishortn.ink#38]
Add a section before the frequently asked question that lists out all the features provided by the service, for now, use your inference to deduce the features to list and as we go ahead, we can modify it to be more in line.

Design is best to your judgement, but it should be simple and straight forward. After the section, add another call to action, sign up

**Comment by kennyAnyi9** [comment]
Well noted

**Comment by AmoabaKelvin** [comment]
If you plan on or prepare to start working on it, please alert me so I assign it to you 😉
