### ISSUE TITLE
replace `toast` component with `sonner` from shadcn/ui

### ISSUE THREAD

**Issue by AmoabaKelvin** [AmoabaKelvin/ishortn.ink#87]

**Comment by RISHIKESHk07** [comment]
@AmoabaKelvin would luv to give it a try , not familiar with next.js but will try , could tell me where is the toast component used as well

**Comment by AmoabaKelvin** [comment]
Hello @RISHIKESHk07 
Thank you very much for looking into this, currently, all the components we use are from [shadcn/ui](https://ui.shadcn.com/docs/components/accordion). There was some previous `toast` component they provided but that has been updated to another component, [Sonner](https://ui.shadcn.com/docs/components/sonner) so we need to make all the necessary updates for our previous `toasts`


The toasts are found mostly in this file: https://github.com/AmoabaKelvin/ishortn.ink/blob/c0b03d5d6c7b0e048ea62e0aeb8b44070bfe0694/src/components/dashboard/link-overview/link-showcase.tsx

You can do a quick search of `toast` in your IDE in case there are other parts where it is located.

**Comment by AmoabaKelvin** [comment]
@RISHIKESHk07 I hope you are doing well!

Any progress on this?

**Comment by RISHIKESHk07** [comment]
Is there Default Unkey and clerk crendentials for .env  , should i make them again ? Do not have much idea my self

**Comment by AmoabaKelvin** [comment]
Sorry about that, @RISHIKESHk07 

I needed to give you a link to the documents as well, so you can go through them and set them up.

Here you go: https://ishortn.mintlify.app/environment-variables
